[project]
name = "lightdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastembed>=0.5.1",
    "wrapt>=1.17.2",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]
